name: flutter_movie_deep_dive_test
description: A movie flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Helps to implement equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.3

  # A composable, multi-platform, Future-based API for HTTP requests.
  http: ^0.13.3

  # Functions that support JSON code generation via the `json_serializable` package.
  json_annotation: ^4.1.0
  
  # Widgets that make it easy to integrate blocs and cubits into Flutter. Built to work with package:bloc.
  flutter_bloc: ^7.3.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  # Tools to write binaries that run builders.
  build_runner: ^2.1.2

  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^5.0.2

  # Mock library for Dart inspired by Mockito.
  mockito: ^5.0.16

  # A utility for providing mocked response to Image.network in Flutter widget tests.
  network_image_mock: ^2.0.1

  flutter_lints: ^1.0.0
  
flutter:
  uses-material-design: true  
  assets:
   - assets/devfest.jpeg